name: 'eds_omop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'trino_eds'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Simple variable definitions
vars:
  omop_cdm_version: '6.0'

# Model configurations
models:
  eds_omop:
    +materialized: table

    staging:
      +materialized: table

    silver:
      +materialized: table
      +full_refresh: true

# Testing configurations
tests:
  +store_failures: true

# Simple hooks
on-run-start:
  - "{{ log('Starting OMOP CDM transformation...', info=true) }}"

on-run-end:
  - "{{ log('OMOP CDM transformation complete!', info=true) }}"