# models/staging/sources.yml
version: 2

sources:
  - name: staging
    database: iceberg
    schema: staging
    description: "Enhanced staging tables populated by Airflow OMOP pipeline"

    tables:
      - name: biological_results_enhanced
        description: "Enhanced biological results with GDPR anonymization and data quality scoring"
        columns:
          # Core identifiers
          - name: measurement_id
            description: "Unique measurement identifier"
            tests:
              - not_null
              - unique

          - name: person_id_hash
            description: "GDPR-anonymized patient identifier"
            tests:
              - not_null

          - name: measurement_source_value
            description: "Laboratory code (LC:xxxx format)"
            tests:
              - not_null

          # Temporal fields
          - name: measurement_datetime
            description: "Measurement datetime (UTC)"
            tests:
              - not_null

          - name: measurement_date
            description: "Measurement date"
            tests:
              - not_null

          # Value fields
          - name: value_as_number
            description: "Numeric measurement value"

          - name: value_as_string
            description: "String measurement value (for categorical results)"

          - name: value_qualifier
            description: "Value qualifier (e.g., >, <, =)"

          - name: unit_source_value
            description: "Measurement unit"

          - name: normality
            description: "Result normality (NORMAL/ABNORMAL/UNKNOWN)"

          - name: abnormal_flag
            description: "Abnormal flag (H/L/N)"

          # Visit context
          - name: visit_id
            description: "Visit identifier"
            tests:
              - not_null

          - name: visit_date
            description: "Visit date"

          - name: provider_id
            description: "Healthcare provider identifier"

          - name: laboratory_uuid
            description: "Laboratory location identifier"

          # Enhanced fields
          - name: value_type
            description: "Value type classification (NUMERIC/CATEGORICAL/ANTIBIOGRAM)"

          - name: bacterium_id
            description: "Bacterium identifier for antibiogram results"

          - name: data_quality_score
            description: "Data quality score (0.0 to 1.0)"
            tests:
              - not_null

          - name: omop_target_domain
            description: "Target OMOP domain (MEASUREMENT/OBSERVATION)"

          # GDPR audit fields
          - name: processing_batch_id
            description: "Processing batch identifier for audit trail"
            tests:
              - not_null

          - name: gdpr_original_hash
            description: "One-way hash of original patient ID for audit"

          - name: source_file
            description: "Source CSV file name"

          - name: load_timestamp
            description: "Timestamp when data was loaded into staging"

  # OMOP vocabulary sources
  - name: silver
    database: iceberg
    schema: silver
    description: "OMOP vocabulary and mapping tables"

    tables:
      - name: omop_concept
        description: "OMOP standard concepts from OHDSI Athena"
        columns:
          - name: concept_id
            description: "Unique concept identifier"
            tests:
              - not_null
              - unique

          - name: concept_name
            description: "Concept name"
            tests:
              - not_null

          - name: vocabulary_id
            description: "Vocabulary identifier (LOINC, SNOMED, etc.)"

          - name: domain_id
            description: "OMOP domain (Measurement, Observation, etc.)"

          - name: standard_concept
            description: "Standard concept flag (S/C/null)"

      - name: concept_map_laboratory
        description: "Laboratory code to LOINC concept mappings"
        columns:
          - name: source_code
            description: "Source laboratory code (LC:xxxx)"
            tests:
              - not_null
              - unique

          - name: target_concept_id
            description: "Target OMOP concept ID"
            tests:
              - not_null

          - name: mapping_confidence
            description: "Mapping confidence score (0.0 to 1.0)"

          - name: mapping_status
            description: "Mapping status (ACTIVE/NEEDS_REVIEW/DEPRECATED)"

      - name: omop_concept_relationship
        description: "OMOP concept relationships"
        columns:
          - name: concept_id_1
            description: "Source concept ID"

          - name: concept_id_2
            description: "Target concept ID"

          - name: relationship_id
            description: "Relationship type"